### ISSUE TITLE
Nested Grouping

### ISSUE THREAD

**Issue by alucab** [seatable/seatable#126]
Nested grouping is in this moment the feature that i really would like to see, at least two levels.

That would enable a huge amount of applications, it is the thing that really kills Seatable wrt Airtable at the moment

Thanks for your job guys

**Comment by freeplant** [comment]
This feature is available in SeaTable enterprise edition.

**Comment by alucab** [comment]
it's not clear from the documentation, the only hting stated is that this is not available at all.
any plan to make it available in the paid version ?

**Comment by freeplant** [comment]
Well, I think I had mis-understood your requirements. I thought you mean nested group for users.

If you mean nested group for rows in a table, it is not available yet. But it will be soon added within a few months for the community edition.

**Comment by alucab** [comment]
thx !

**Comment by agrimpelhuber** [comment]
I strongly support this feature suggestion, and like to add a few arguments.

As noted before, such a feature can be considered as a recursive, indefinite grouping: Taking one field of the table that refers to the table itself, i.e. a "parent" (generic nodes) or "reports to" (employee table) relation. Using a table field, this would

* not only make the data transparent which is the basis for the hierarchy (see example below)
* but would also make it possible to have _multiple hierarchies_ in one table
* finally make this a killer feature, because hierarchies are _everywhere_ (outlines, categories, projects, org charts, topics ...)

Last, but not least, this would be a killer feature that sets seatable apart from airtable. Airtable has an "org chart" plugin, but no editable table view. What I mean with this is illustrated by a screen shot from OpenProject, where you can have infinite levels of tasks, subtasks, milestones etc.

![image](https://user-images.githubusercontent.com/35150551/120796429-1ae6ae80-c53b-11eb-942b-430969d6af36.png)

Here's basically the same data in seatable, plus a table relation "Child of". Imagine a view option that could take this field and create an editable table view - OpenProject would be obsolete:

![image](https://user-images.githubusercontent.com/35150551/120798349-8598e980-c53d-11eb-9cea-6f57f5d30d95.png)

The current grouping, with it's single level, is a poor replacement. And not even that.

![image](https://user-images.githubusercontent.com/35150551/120798503-bda02c80-c53d-11eb-9d1d-7f799179ab51.png)

**Comment by freeplant** [comment]
The feature has been implemented in the latest version.

**Comment by agrimpelhuber** [comment]
Thanks for implementing this!

However, after testing, I consider this a very limited replacement for a real hierarchy, if it even is one. So my original comment can now be considered as a separate feature request. And an important one, because Seatable could be so much more versatile with a true hierarchy implemented.
