### ISSUE TITLE
Unable to connect to web

### ISSUE THREAD

**Issue by subzero355** [seatable/seatable#46]
Hi,
Followed the guide for install instructions and I am unable to connect to the web. The docker is started and firewall is disabled. I have changed the port for seatable to expose 0.0.0.0:7443 > 443. When I checked the logs, I get below message,
"docker logs seatable
*** Running /etc/my_init.d/01_init.sh...
*** Booting runit daemon...
*** Runit started as PID 15
*** Running /templates/enterpoint.sh...
2020-05-08 17:40:02 Conf exists
2020-05-08 17:40:02 Nginx ready
nginx: [emerg] open() "/etc/nginx/sites-enabled/default" failed (2: No such file or directory) in /etc/nginx/nginx.conf:25
2020-05-08 17:40:02 This is a idle script (infinite loop) to keep container running.
"

**Comment by chug2k** [comment]
I had this problem, and it was me not having the right domain setup for LetsEncrypt. (I was trying to use an IP address, which is _not_ how that works.)

But the steps to debug:

* `docker exec -it seatable bash` - start a bash shell so you can navigate around.
* check to see if `nginx.conf` actually does exist. It *should* exist at `/opt/seatable/conf/nginx.conf` but sometimes if you have an error seatable decides to delete it. 
* check the logs, either `init.log` or `seafile.log` in `/opt/seatable`. that should tell you where the problem is.
